<a href="https://colab.research.google.com/github/madawi84/it-cert-automation-practice/blob/master/CT_Module_9_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1-Download the iris.csv file, example: https://gist.github.com/netj/8836201. From this file the label (target) is defined with the ‘variety’ column and the features with ‘epal.length’, ‘sepal.width’, ‘petal.length’, ‘petal.width’ columns.**

In [7]:
#loading data sets
from sklearn import datasets
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

load the iris dataset

In [8]:
iris = load_iris()
#ptint the feature names and the target 
print(iris.feature_names)
print(iris.target_names)
#print the shape of iris data set
iris.data.shape

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


(150, 4)

**2-Preprocess the iris.csv file by label encoding the target ‘variety’ column.**

In [9]:
#import sklearn.preprocessing Model to convert categorical data of the target to numeric data
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
le = preprocessing.LabelEncoder()
# Encode labels in column 'variety'.
iris.target_names= le.fit_transform(iris.target_names)
#display the variety values after encoding
print(iris.target_names)


[0 1 2]


**3-Apply the following Machine Learning classification models: K Nearest Neighbors and Random Forests.**

First shuffle the data to randomize it, then split the data into a training set and a testing set to prepare to train and test the model.




In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=0)

printing the size of each dataset and target set



In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(112, 4)
(38, 4)
(112,)
(38,)


**A)K Nearest Nighbors**

create the KNeighborsClassifier estimator object

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

invoke the KNeighborsClassifier object’s fit method to load the sample training set and target training set into the estimator

In [13]:
#create the estimator
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

Making predictions

In [14]:
#Calling the predict method with data trin set to predicte the class of each test sample:
predicted = knn.predict(X=X_test)
expected = y_test

# Visualizing the Expected vs. Predicted for the first 10 samples
df = pd.DataFrame()
df['Expected'] = pd.Series(expected[:10])
df['Predicted'] = pd.Series(predicted[:10])
print(df)

#locate all the incorrect predictions for the entire test set.
incorrect = [(p, e) for (p, e) in zip(predicted, expected) if p != e]
print(incorrect)

   Expected  Predicted
0         2          2
1         1          1
2         0          0
3         2          2
4         0          0
5         2          2
6         0          0
7         1          1
8         1          1
9         1          1
[(2, 1)]


**4A-Calculate the following classification metrics to validate the model: Accuracy Score, Confusion Matrix and Classification Report.**

 **Accuracy Score**

In [15]:
print(f'{knn.score(X_test, y_test):.2%}')

97.37%


**Confusion Matrix**

In [16]:
#import the confusion_matrix module
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_true=expected, y_pred=predicted)
print(confusion) 

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


**Classification Report**

In [17]:
#import classification_report module
from sklearn.metrics import classification_report
names = [str(i) for i in iris.target_names]
print(classification_report(expected, predicted, target_names=names))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



**B)Random Forest**

In [18]:
#Import randomforestclassifier Model
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=0)
#create the classifier
rfc=RandomForestClassifier(n_estimators = 100)
#Train the model using the training sets
rfc.fit(X_train,y_train)
#performing predictions on the test dataset
y_pred = rfc.predict(X_test)


**4B-Calculate the following classification metrics to validate the model: Accuracy Score, Confusion Matrix and Classification Report.**

 **Accuracy Score**

In [ ]:
print(f'{rfc.score(X_test, y_test):.2%}')

97.37%


**Confusion Matrix**

In [ ]:
confusion = confusion_matrix(y_true=expected, y_pred=predicted)
print(confusion) 

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


**Classification Report**

In [ ]:
names = [str(i) for i in iris.target_names]
print(classification_report(expected, predicted, target_names=names))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

